# Generated by Django 2.2.1 on 2019-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='test_field',
            field=models.CharField(default='ttt', max_length=50),
        ),
    ]
