# Generated by Django 2.2.1 on 2019-05-26 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checks', '0003_auto_20190525_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Checks',
        ),
    ]
