# Generated by Django 2.2.1 on 2019-05-26 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checks', '0004_auto_20190526_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checks',
            new_name='Check',
        ),
    ]
